<!DOCTYPE html>
<html>
<head>
  <title>Dodaj do Kalendarza</title>
</head>
<body>
  <button onclick="openCalendar()">Dodaj badanie do Kalendarza Google</button>

  <script>
    function openCalendar() {
      const now = new Date();
      now.setDate(now.getDate() + 28);

      const startDate = now.toISOString().replace(/[-:]|\.\d{3}/g, '').slice(0, 15) + '00';
      const endDate = new Date(now.getTime() + 30 * 60 * 1000) // 30 minut
        .toISOString().replace(/[-:]|\.\d{3}/g, '').slice(0, 15) + '00';

      const url = `https://calendar.google.com/calendar/render?action=TEMPLATE&text=Gabinet+Weterynaryjny+-+badanie+profilaktyczne&details=Badanie+profilaktyczne+w+gabinecie+weterynaryjnym&dates=${startDate}/${endDate}`;

      window.open(url, '_blank');
    }
  </script>
</body>
</html>
